### PR TITLE
Add preloads to :npm-module target

### PR DESCRIPTION
**Pull request by arichiardi**
Attempting it, hopefully I am doing it right.

### CODE REVIEW

**Comment by thheller** [comment]
`:preloads` are not easily possible in `:npm-module`.

For preloads to work we need an entry point to ensure that they are "preloaded" before loading that entry. `:npm-module` has no defined entry since you can basically use any namespace at any point. Adding it to the entries like your PR would cause it to be compiled but not loaded.

The same is true for the REPL code in `:npm-module`. It currently needs to be loaded manually as the compiler only compiles it but cannot ensure that it is loaded.

**Comment by arichiardi** [comment]
Oh thanks that's clear, of course! :smile: So maybe `:npm-module` target should have a `:repl-main` entry just for repl development? We could preload in that namespace then.

**Comment by thheller** [comment]
The primary purpose of `:npm-module` is interfacing with JS tools that post process the result, e.g. using CLJS code directly in a `webpack` build. Since the generated code behaves and looks like CommonJS that works fine.

REPL integration for this is secondary and pretty much a non-goal since it cannot be guaranteed that the REPL will actually still work after the JS tool is done with the code (quite often it doesn't). `:preloads` is sort of in the same area.

That is is primary reason more specific targets exist to avoid such incompatibilities and provide more optimized output for the given target.

If you are experimenting with this because of `:azure-fn` then technically you'd use `:npm-module` style output in one directory and just have it generate additional files in `fn1/index.js` which just `module.exports = require("../cljs/my.app").exports;`. Since each `fn` would then have a clearly defined entry you could easily add preloads.

`:npm-module` is not the right place to do this.

**Comment by arichiardi** [comment]
Got it, so are you suggesting me to have two (or more) targets - one for working at the REPL and one for compiling?

**Comment by thheller** [comment]
If you just want a REPL use `shadow-cljs node-repl` or `shadow-cljs browser-repl`.

**Comment by thheller** [comment]
You can get a REPL if you do it manually.
```
if (process.env.NODE_ENV === "development") {
   require("./path-to-your-cljs/shadow.cljs.devtools.client.browser");
}
```

Ideally that should be done in your normal JS entry before any other CLJS is loaded. I cannot guarantee that this will always work because `webpack` and others sometimes do weird things to the code which can prevent the REPL from working correctly or at all.

**Comment by thheller** [comment]
Conditional requires are terrible indeed. You could use a build hook to output an empty `shadow.cljs.devtools.client.browser.js` after `compile`. It is not copied to the output-dir since it isn't compiled as `compile` does not support the REPL anyways. REPL needs a running `watch`.

**Pull request closed without merging**
