### PR TITLE
turn modules uris to absolute urls to play well in Chrome DevTools

### PR DESCRIPTION
**Pull request by darwin**
I have an app which uses dynamic modules. I noticed that both in dev mode and also in release mode modules are loaded via relative urls which do not play well with DevTools. The problem is that they are kept in `(no domain)` section of the DevTools resources tree, instread being located at expected places next to other resources.

see https://github.com/thheller/shadow-cljs/issues/637 for previous discussion

### CODE REVIEW

**Comment by thheller** [comment]
I'm fairly certain this impl will break when using `:asset-path "js"` (ie. not an absolute path).

If you want you can call `(shadow.loader/init "https://wherever.you.are")` in your `:init-fn` (before using other modules. Maybe you can do that for now?

**Comment by darwin** [comment]
I just tried to call `(shadow.loader/init ...)` in `:init-fn` if my main module. But that does is called after auto-generated shadow.loader.init call in `cljs-runtime/shadow.module.main.append.js` (and throws).

Also I don't think that prefix would be used in `shadow$modules.uris`. The problem is that google loader uses eval for executing downloaded code and appends "# sourceURL=..." with relative url based on `shadow$modules.uris`

**Comment by darwin** [comment]
btw. in my project I'm using
```
:output-dir    "public/.compiled"
:asset-path    "/.compiled"
```

And it works - uris are relative to document (index page) - maybe for google loader to load them without further rebasing?

**Comment by darwin** [comment]
Please see my reviewed version. I included `location.pathname` and guard against double slashes.

**Comment by thheller** [comment]
`:asset-path    "/.compiled"` is an absolute path.

If you are calling init you must set `:module-loader-init false` in your build config so shadow-cljs doesn't inject the auto init.

I'm sorry but I'm not comfortable with a path handling change like this. It is already far too complicated and I'd much rather replace the entire impl than adding more complexity. You can get the behavior you need by calling init manually + the config setting.

**Pull request closed without merging**
