### PR TITLE
Add re-frame-flow to Examples

### PR DESCRIPTION
**Pull request by ertugrulcetin**

### CODE REVIEW

**Comment by thheller** [comment]
This doesn't seem to fit the Example category? Can you move it into the Libraries section?

**Comment by ertugrulcetin** [comment]
@thheller sure, done.

**Comment by thheller** [comment]
BTW in your example you tell the user to require your library just to add the `clear-cache!` call. You may also just add that hint directly to your `(defn ^:dev/after-load clear-cache! [] ...)` so the user never has to add it. Apps can have many of these and due to loading order is should more or less be guaranteed that yours runs before user code. Or you can add it via the `preload` namespace as well.

**Comment by ertugrulcetin** [comment]
@thheller thanks you, did not know that. Let me add it!

**Pull request merged**
