### PR TITLE
More robust cli health check

### PR DESCRIPTION
**Pull request by lins05**
I have experienced a problem that the shadow-cljs java process exited itself, after some debugging it turned out the health check to the cli-port failed for no reason. I think it makes sense to retry a few times (here I use 3) before aborting.

### CODE REVIEW

**Comment by thheller** [comment]
Are you able to track down why it would fail once but not 3 times in a row?

It was reported before that this was happening on macOS. I would like to have some insight about why a localhost TCP connect would occasionally fail? Does this happen in some specific situations? Waking up from sleep? Switching WiFi networks? Any clue at all?

**Comment by lins05** [comment]
I tried to understand how the tcp server in the cli part works, but was stuck when trying to figure out how this piece of code work:

https://github.com/thheller/shadow-cljs/blob/fb4c00030178100374aa9652f382f1f8e3538eab/src/main/shadow/cljs/npm/cli.cljs#L95-L123

I read the docs but couldn't figure out how `net.Server.listen` is able to accept a function as parameter.

**Comment by thheller** [comment]
It is this variant with just the last callback argument. I'm not specifying a port since I want it to pick a random one.

https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback

**Comment by thheller** [comment]
Just a note: I want this to be more robust BUT the issue I have with this method is that if the `node` process is actually dead the JVM process will linger around for 20-ish seconds when it shouldn't because it'll run through all attempts and waiting 5sec each time. Depending on how it takes to fail it might take an addition 1sec each to reach the timeout.

So if the `node` process is killed intentionally to restart because of changing deps or something the old one might still be around when the new on is starting.

So I'd much rather find out WHY it is failing in the first place and fix that. Maybe it should just use a different method entirely that doesn't involve a TCP socket at all.

**Comment by lins05** [comment]
I tried to isolate the problem by using a python script (https://gist.github.com/lins05/aaa6cd8a4b5e10cfdf8b1a166e1d10d4) to constantly ping the node health check port and it got stuck once a while

> the issue I have with this method is that if the node process is actually dead the JVM process will linger around for 20-ish seconds when it shouldn't

@thheller maybe we can check for `SocketTimeoutException` (when node process dies it's `ConnectException`) 

Here is the error msg I got:

```
[2019-11-17 08:36:24.515 - FINE] :shadow.cljs.devtools.server/cli-check-failed - {:cli-port 58194}
SocketTimeoutException connect timed out
        java.net.PlainSocketImpl.socketConnect (PlainSocketImpl.java:-2)
        java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:350)
        java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:206)
        java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:188)
        java.net.SocksSocketImpl.connect (SocksSocketImpl.java:392)
        java.net.Socket.connect (Socket.java:589)
        shadow.cljs.devtools.server/ping-node-process (server.clj:213)
        shadow.cljs.devtools.server/ping-node-process (server.clj:203)
        shadow.cljs.devtools.server/create-cli-checker/thread-fn--17668 (server.clj:240)
        java.lang.Thread.run (Thread.java:748)
```

Though I still couldn't figure out why this happens from time to time.

**Comment by thheller** [comment]
I switched the check to using a regular file instead of a full TCP server. Should be more reliable.

**Comment by lins05** [comment]
Thanks!

**Pull request closed without merging**
