### PR TITLE
Introduce :deps :aliases merge from .shadow-cljs/config.edn

### PR DESCRIPTION
**Pull request by arichiardi**
This patch provides a way to have system-configured `:aliases` that conjoin to
the local project-specific one in a shadow build based on `deps.edn`.

It also add a couple of specs that validate the new `config.edn`. Of course
adding `:deps` to `config.edn` is optional.

### CODE REVIEW

**Comment by arichiardi** [comment]
I thought this would avoid the hassle of having to do:

`yarn shadow-cljs watch dev -A:cider`

for cider users and it still actually does not work...so my question for @thheller would be, what am I missing to makes so that I can control that `-A:cider` alias addition?

**Comment by arichiardi** [comment]
For completeness my `println`-ed merged build is:

```clojure
{:node-modules {:install-cmd [yarn add --network-concurrency 1 :packages]}
 :deps {:aliases [:cider :dev :test]}
 :cache-root .shadow-cljs
 :builds ...}
```

**Comment by thheller** [comment]
I'm sorry but I don't think I want to support this.

I kinda want everything build related to not be in `~/.shadow-cljs/config.edn` since that might have the effect of things building on one machine but not another. I realize that you want it for tooling but allowing something general like this will probably end up getting abused.

The merge would also need to happen in the CLJS part since it affects how everything is started and only doing it in the CLJ part is too late.

I'll think about it for a day or so.

**Comment by arichiardi** [comment]
Oh...too bad.

I guess one of the pain-point now for my team is that we cannot "merge-in" system-specific dependencies - like `cider-nrepl` in case of Emacs users.

Of course I could use an environment variable but it feels it should be embedded in the tool? Just my gut feeling.

**Comment by thheller** [comment]
I do want to support the tooling aspect. I just rather want to have something like `:cider true` than manually tweaking the classpath that enables other sort of footguns.

**Comment by arichiardi** [comment]
Oh ok cool sorry did not understand properly the criticism then :wink:

**Comment by arichiardi** [comment]
Hi Thomas any more hint on this?

Your `:cider true` implies maintaining package versions and merging into the deps automatically if I understand it right. 

No rush on this but it would be really awesome.

Also, cider can inject itself if there was a way to run `shadow-cljs` with additional deps - out of band

**Comment by thheller** [comment]
I thought `cider` was already injecting itself when you start it via `jack-in`?

`shadow-cljs -d cider-nrepl:0.19.0 server` will inject the extra dep on startup.

**Comment by arichiardi** [comment]
Oh, does it work for deps edn? Yes I think I mislead you there, because this still requires passing parameters at the command line, which I wanted to avoid :smile:

**Comment by thheller** [comment]
So my stance right now is to use `deps.edn`. It can already do everything you are asking for without me doing anything.

You could just have your team each add an `:editor` profile to their own `~/.clojure/deps.edn`. Whatever their editor requires they can add there. In `shadow-cljs.edn` you just add `:deps {:aliases [:editor :whatever-else]}`.

Not sure it makes sense configuring this in 2 places otherwise.

**Comment by arichiardi** [comment]
ah ok convention there, might be a good idea. Still feels hackish because Cursive does not require anything and their `:editor` would be empty

**Comment by thheller** [comment]
I decided to introduce the new concept of a User Config which lets you add dependencies (and/or `:deps-aliases`) on a per-user basis via `~/.shadow-cljs/config.edn`. Things like `cider-nrepl` should definitely go there.

**Comment by arichiardi** [comment]
:+1:

**Pull request closed without merging**
