### PR TITLE
Readme guide

### PR DESCRIPTION
**Pull request by jiyinyiyong**
Preview at https://github.com/jiyinyiyong/shadow-cljs/tree/readme-guide

For people who are not familiar with shadow-cljs, it's much more important to show them how to use shadow-cljs to compile the code. And they barely read large chunks of text, except for details in the docs.

This is a draft though. Maybe the README can be updated also since half a year has passed.

### CODE REVIEW

**Comment by thheller** [comment]
I do agree that the README should be re-structured but all the info you added is basically already included just further down.

I have finished almost all the work I wanted to do for `v2`, just a few smaller things remain.

When that is done I'll focus on the documentation and write some step-by-step guides for the most common scenarios.

**Comment by jiyinyiyong** [comment]
Glad to see v2 approaching~

I just want to argue that people don't always read the "further down" part. So we always need a very short piece to tell them how to use shadow-cljs, especially for the beginners.

**Comment by thheller** [comment]
The problem is that this stuff is complicated. There is no "short" way that could possibly cover all the things you need to know to use this properly.

I re-structured the README a bit but really I don't think there is much to be gained by this. Real beginners are better served by having an actual example with a walk-through but this is out of scope for the README.

**Comment by thheller** [comment]
You have written a guide in Chinese? What was the link again? I added a "Guides" section to the README which should link to guides for the most common setups.

**Comment by jiyinyiyong** [comment]
By the "short" one I'm trying to encourage beginners to go on his/her first step. After they compiled a first project, then he/she gets **an overview of how shadow-cljs is doing**. Then reading docs is less boring. I would agree that API docs is always boring though.

**Comment by thheller** [comment]
As much as I hate templates they are are better when getting started.

I might create some actual templates that take care of the boring stuff and drop you right into a working example.

**Comment by jiyinyiyong** [comment]
There was one http://clojure-china.org/t/shadow-cljs/666 .

However it's too old. I'm going to update that post tonight.

**Comment by jiyinyiyong** [comment]
Compared to templates I prefer copy pasting examples better. By pasting code myself I can remember the steps of using it better.

Anyway adding templates brings much help to beginners...

**Comment by jiyinyiyong** [comment]
end up writing a new post on shadow-cljs 2.x https://segmentfault.com/a/1190000011499210

**Comment by thheller** [comment]
I linked it from the README. Since I do not understand a word and google translate doesn't help much I hope that I picked the correct title ` shadow-cljs 2.x 使用教程`.

**Comment by jiyinyiyong** [comment]
Yeah, "shadow-cljs 2.x 使用教程" is the title.

**Pull request closed without merging**
