### PR TITLE
[#371] Support file scheme for css reloading

### LINKED ISSUE #371: css reloading broken in electron
Victim of the relative path change. Needs special case for `file:` urls.

### PR DESCRIPTION
**Pull request by endenwer**
fixes #371 

Support for reloading css with file scheme. Fix css reloading in electron.

Tested with:
https://github.com/shadow-cljs/quickstart-browser
https://github.com/ahonn/shadow-electron-starter

### CODE REVIEW

**Comment by thheller** [comment]
I need to confirm but I think this breaks css-reloading on relative paths via HTTP.

I general I think it should just skip all the resolve stuff if `js/document.location.protocol` is `file:` and just compare the paths instead.

**Comment by endenwer** [comment]
I don't think it will break relative paths because it uses previous uri for new css tag. So if old one was working when new should work as well.
And the resolve stuff also required for file scheme because `node-abs` will look like this `/css/main.css` if href is `css/main.css` (`/` at the beginning). This is require to compare it with file path.

**Comment by thheller** [comment]
The point is that the `node-uri` path may not be correct anymore.

Assuming that the user starts out at `/` and `css/foo.css` was included. The user now push-state routed to `/bar`. Including `css/foo.css` again will now end up loading `/bar/css/foo.css` which is incorrect.

I'll test this later.

**Comment by thheller** [comment]
This should be fixed in `2.6.3`. Decided to clean the code up a bit by extract a proper function.

**Pull request closed without merging**
