### PR TITLE
Add a badge to Clojurians

### PR DESCRIPTION
**Pull request by jiyinyiyong**
Generated with https://shields.io/

https://img.shields.io/badge/Clojurians-shadow--cljs-lightgrey.svg

[](https://clojurians.slack.com/messages/C6N245JGG/)

### CODE REVIEW

**Comment by jiyinyiyong** [comment]
Maybe more to try:
Version [](https://img.shields.io/npm/v/shadow-cljs.svg)
Download count(week) [](https://img.shields.io/npm/dw/shadow-cljs.svg)
Download count(month) [](https://img.shields.io/npm/dm/shadow-cljs.svg)

BTW, quite impressive downloads yesterday...
https://www.npmjs.com/package/shadow-cljs

```
546 downloads in the last day
1,927 downloads in the last week
2,019 downloads in the last month
```

**Comment by jiyinyiyong** [comment]
Maybe more to try:
Version [](https://img.shields.io/npm/v/shadow-cljs.svg)
Download count(week) [](https://img.shields.io/npm/dw/shadow-cljs.svg)
Download count(month) [](https://img.shields.io/npm/dm/shadow-cljs.svg)

BTW, quite impressive downloads yesterday...
https://www.npmjs.com/package/shadow-cljs

```
546 downloads in the last day
1,927 downloads in the last week
2,019 downloads in the last month
```

**Comment by thheller** [comment]
Maybe when 2.0 is released and working properly. This badges don't really mean much IMHO.

I don't quite trust those numbers either since they are so far off from the clojars numbers.

https://clojars.org/thheller/shadow-cljs

`361 Downloads` total for all releases which is a required download that is always done when launching `shadow-cljs`. So either it doesn't start for most people or `npm` is counting weirdly.

**Comment by jiyinyiyong** [comment]
So only ones interested is the version badge [Clojars Project](https://clojars.org/thheller/shadow-cljs)

**Pull request merged**
